#!/usr/bin/env python3

import itertools
import sys
from collections import defaultdict
from pathlib import Path

import click
import jinja2

from tools.codegen_db_plugin.proto import Catalog, Column, File, GenerateRequest, GenerateResponse, Parameter, Query

MODELS_TEMPLATE = """\
# Code generated by sqlc. DO NOT EDIT.
import dataclasses

{% for table in tables -%}
@dataclasses.dataclass(slots=True)
class {{ table.class_name }}:
{%- for column in table.columns %}
    {{ column.name }}: {{ column.python_type }}
{%- endfor %}

{% endfor -%}
"""

QUERIES_TEMPLATE = '''\
# Code generated by sqlc. DO NOT EDIT.
import dataclasses
import sqlite3
from collections.abc import Iterator

from __codegen__ import models

{% for query in queries -%}
{%- if query.needs_custom_dataclass -%}
@dataclasses.dataclass(slots=True)
class {{ query.custom_dataclass_name }}:
{%- for column in query.columns %}
    {{ column.name }}: {{ column.python_type }}
{%- endfor %}

{% endif -%}
{%- endfor -%}
{%- for query in queries -%}
{{ query.constant_name }} = """\\
{{ query.text }}
"""

def query_{{ query.name }}(conn: sqlite3.Connection{{ query.params_signature }}) -> {{ query.return_type }}:
{%- if query.cmd == ":exec" %}
    conn.execute({{ query.constant_name }}, {{ query.param_tuple }})
{%- elif query.cmd == ":execresult" %}
    return conn.execute({{ query.constant_name }}, {{ query.param_tuple }})
{%- elif query.cmd == ":execlastid" %}
    cursor = conn.execute({{ query.constant_name }}, {{ query.param_tuple }})
    return cursor.lastrowid or 0
{%- elif query.cmd == ":one" %}
    row = conn.execute({{ query.constant_name }}, {{ query.param_tuple }}).fetchone()
    if row is None:
        raise ValueError("query {{ query.name }}: expected one row, got none")
{%- if query.columns %}
    {%- if query.columns|length == 1 %}
    return {{ query.columns[0].assignment }}
    {%- elif query.needs_custom_dataclass %}
    return {{ query.custom_dataclass_name }}(
    {%- else %}
    return models.{{ query.model_name }}(
    {%- endif %}
{%- if query.columns|length > 1 %}
{%- for column in query.columns %}
        {{ column.name }}={{ column.assignment }},
{%- endfor %}
    )
{%- endif %}
{%- else %}
    return row
{%- endif %}
{%- elif query.cmd == ":many" %}
    rows = conn.execute({{ query.constant_name }}, {{ query.param_tuple }}).fetchall()
    for row in rows:
{%- if query.columns %}
        {%- if query.columns|length == 1 %}
        yield {{ query.columns[0].assignment }}
        {%- elif query.needs_custom_dataclass %}
        yield {{ query.custom_dataclass_name }}(
        {%- else %}
        yield models.{{ query.model_name }}(
        {%- endif %}
{%- if query.columns|length > 1 %}
{%- for column in query.columns %}
            {{ column.name }}={{ column.assignment }},
{%- endfor %}
        )
{%- endif %}
{%- else %}
        yield row
{%- endif %}
{%- endif %}

{% endfor -%}
'''

SQLITE_TO_PYTHON_TYPES = {
    "text": "str",
    "varchar": "str",
    "character": "str",
    "nchar": "str",
    "nvarchar": "str",
    "clob": "str",
    "integer": "int",
    "int": "int",
    "tinyint": "int",
    "smallint": "int",
    "mediumint": "int",
    "bigint": "int",
    "int2": "int",
    "int8": "int",
    "real": "float",
    "double": "float",
    "double precision": "float",
    "float": "float",
    "numeric": "float",
    "decimal": "float",
    "boolean": "bool",
    "blob": "bytes",
    "datetime": "str",
    "date": "str",
}


def generate_models(catalog: Catalog) -> str:
    tables = [
        {
            "class_name": f"{_snake_to_pascal(_depluralize_table_name(table.rel.name))}Model",
            "columns": [
                {"name": column.name, "python_type": _map_sqlite_type_to_python(column)} for column in table.columns
            ],
        }
        for table in itertools.chain(*[s.tables for s in catalog.schemas])
        if not table.rel.name.startswith("_yoyo")
    ]
    return jinja2.Template(MODELS_TEMPLATE).render(tables=tables)


def generate_queries(queries: list[Query], catalog: Catalog | None = None) -> str:
    def get_param_name(param: Parameter) -> str:
        return param.column.name or f"p{param.number}"

    def get_model_name(query: Query) -> str:
        if query.insert_into_table and query.insert_into_table.name:
            return _snake_to_pascal(_depluralize_table_name(query.insert_into_table.name)) + "Model"
        if catalog and query.columns and (table_name := _does_query_return_model(query, catalog)):
            return _snake_to_pascal(_depluralize_table_name(table_name)) + "Model"
        return f"{_snake_to_pascal(query.name)}Result"

    def needs_custom_dataclass(query: Query) -> bool:
        if not query.columns or not catalog:
            return False
        return not _does_query_return_model(query, catalog)

    def is_single_value_query(query: Query) -> bool:
        return bool(query.columns and len(query.columns) == 1)

    query_data = [
        {
            "name": query.name,
            "constant_name": query.name.upper(),
            "text": query.text,
            "cmd": query.cmd,
            "params_signature": (
                f", *, {', '.join(f'{get_param_name(p)}: {_map_sqlite_type_to_python(p.column)}' for p in query.params)}"
                if query.params
                else ""
            ),
            "return_type": {
                ":exec": "None",
                ":execresult": "sqlite3.Cursor",
                ":execlastid": "int",
                ":one": (
                    _map_sqlite_type_to_python(query.columns[0])
                    if is_single_value_query(query)
                    else (get_model_name(query) if needs_custom_dataclass(query) else f"models.{get_model_name(query)}")
                )
                if query.columns
                else "sqlite3.Row",
                ":many": (
                    f"Iterator[{_map_sqlite_type_to_python(query.columns[0])}]"
                    if is_single_value_query(query)
                    else (
                        f"Iterator[{get_model_name(query)}]"
                        if needs_custom_dataclass(query)
                        else f"Iterator[models.{get_model_name(query)}]"
                    )
                )
                if query.columns
                else "Iterator[sqlite3.Row]",
            }.get(query.cmd, "None"),
            "param_tuple": (
                "(" + ", ".join(get_param_name(p) for p in query.params) + ("," if len(query.params) == 1 else "") + ")"
                if query.params
                else "()"
            ),
            "model_name": get_model_name(query) if query.columns else None,
            "columns": [
                {
                    "name": col.name,
                    "python_type": _map_sqlite_type_to_python(col),
                    "type_name": col.type.name.lower(),
                    "assignment": f"row[{i}]",
                }
                for i, col in enumerate(query.columns)
            ]
            if query.columns
            else None,
            "needs_custom_dataclass": needs_custom_dataclass(query),
            "custom_dataclass_name": get_model_name(query) if needs_custom_dataclass(query) else None,
            "is_single_value": is_single_value_query(query),
        }
        for query in queries
    ]

    return jinja2.Template(QUERIES_TEMPLATE).render(queries=query_data)


# -- Private helpers -----------------------------------------------------------


def _snake_to_pascal(name: str) -> str:
    return "".join(word.capitalize() for word in name.split("_"))


def _map_sqlite_type_to_python(column: Column) -> str:
    type_name = column.type.name.lower()
    python_type = SQLITE_TO_PYTHON_TYPES.get(type_name, "str")
    return f"{python_type} | None" if not column.not_null else python_type


def _depluralize_table_name(table_name: str) -> str:
    if table_name.endswith("ies"):
        return table_name[:-3] + "y"
    elif table_name.endswith("ves"):
        return table_name[:-3] + "f"
    elif table_name.endswith(("ses", "ches", "xes")):
        return table_name[:-2]
    elif table_name.endswith("s") and not table_name.endswith("ss"):
        return table_name[:-1]
    return table_name


def _does_query_return_model(query: Query, catalog: Catalog) -> str | None:
    if query.columns and len({c.table.name for c in query.columns if c.table and c.table.name}) == 1:
        table_name = next(c.table.name for c in query.columns if c.table and c.table.name)
        table_def = next(
            (t for s in catalog.schemas for t in s.tables if t.rel.name == table_name),
            None,
        )
        if table_def and {c.name for c in query.columns} == {c.name for c in table_def.columns}:
            return table_name
    return None


def _main() -> None:
    request = GenerateRequest().parse(sys.stdin.buffer.read())
    response = GenerateResponse()

    # Package init.
    response.files.append(File(name="__codegen__/__init__.py", contents=b""))

    # Models.
    models_content = generate_models(request.catalog)
    response.files.append(File(name="__codegen__/models.py", contents=models_content.encode("utf-8")))

    # Queries: group by source filepath and emit one queries.py per directory.
    queries_by_filepath: dict[str, list[Query]] = defaultdict(list)
    for query in request.queries:
        queries_by_filepath[query.filepath].append(query)
    cwd = str(Path.cwd().absolute())
    for filepath, queries in queries_by_filepath.items():
        sql_path = Path(filepath)
        assert sql_path.name == "queries.sql"
        output_dir = sql_path.parent / "__codegen__"
        output_path = output_dir / "queries.py"
        init_path = output_dir / "__init__.py"
        response.files.append(File(name=str(init_path).removeprefix(cwd).lstrip("/"), contents=b""))
        queries_content = generate_queries(queries, request.catalog)
        response.files.append(
            File(name=str(output_path).removeprefix(cwd).lstrip("/"), contents=queries_content.encode("utf-8"))
        )

    sys.stdout.buffer.write(bytes(response))


@click.command()
@click.argument("service_method", required=True)
def main(service_method: str | None = None) -> None:
    assert service_method == "/plugin.CodegenService/Generate", f"Unexpected service method: {service_method}"
    _main()


if __name__ == "__main__":
    main()
